### ISSUE TITLE
[FEAT] Add support for lifecycle ignored tags

### ISSUE THREAD

**Issue by mloskot** [claranet/terraform-azurerm-rg#2]
### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I'm wondering if it would be possible to extend the default tags with new tags indicating who/what and when created a particular resource group, that is, something like:

```hcl
  tags = {
    created_at = timestamp()
    created_by = data.azuread_directory_object.terraform.object_id
  }
```

Perhaps it could be added via a new set of tags, along with `default` and `extra`, and controlled with new variable `creator_tags_enabled`.

Perhaps such feature would be sensible across all modules creating resources where `tags` are supported.
I'd be interested to hear your comments on this idea.

### New or Affected Resource(s)/Data Source(s)

azurerm_resource_group

### Potential Terraform Configuration

```hcl
resource "azurerm_resource_group" "main" {
  name     = data.azurecaf_name.main_rg.result
  location = module.azure_region.location

  tags = {
    created_at = timestamp()
    created_by = data.azuread_directory_object.terraform.object_id
  }
```

**Comment by Shr3ps** [comment]
Hello @mloskot ,
Thanks for your suggestion!

At Claranet we already handle this with our internal tagging policy and this module: https://github.com/claranet/terraform-claranet-default-tags

I think you may want to create your own module with your needs. Adding theses default tags on every modules we have will requires lots of maintenance.

**Comment by mloskot** [comment]
Hi @Shr3ps, although such module is a very neat idea, I have just noticed I missed a very important detail in my suggestion: `lifecycle` and `ignore_changes`. I meant tags which are created once per a resource lifetime:

```hcl
resource "azurerm_resource_group" "main" {
  name     = data.azurecaf_name.main_rg.result
  location = module.azure_region.location

  tags = {
    created_at = timestamp()
    created_by = data.azuread_directory_object.terraform.object_id
  }

  lifecycle {
    ignore_changes = [
      tags["created_at"],
      tags["created_by"],
    ]
  }
```

AFAIK, there is no way to inject such `lifecycle` configuration into resources created by modules. Unless, source code of such modules is modified.

> Adding theses default tags on every modules we have will requires lots of maintenance.

Yes, I'm aware this issue may be a blocker here.

**Comment by Shr3ps** [comment]
Hey,

For your tag `created_at` (which IMO should be `updated_at` instead), no lifecycle ingore_changes is needed if you use a  time_static resource (https://registry.terraform.io/providers/hashicorp/time/latest/docs/resources/static) instead of the `timestamp()` builtin which is evaluated every time.

and for your `created_by`,  I don't get also why you need to ignore it, best practices would be to use a CD/pipeline to apply terraform stacks, which means using an Identity, a Service Principal or a Service account - that don't change.

**Comment by mloskot** [comment]
@Shr3ps 
> no lifecycle ingore_changes is needed if you use a time_static resource

I was not aware of this module. Thanks a lot @Shr3ps !

>  for your created_by, I don't get also why you need to ignore it, best practices would be to use a CD/pipeline to apply terraform stacks, which means using an Identity, a Service Principal or a Service account - that don't change.

Yes, you are right about the pipelines recommendation.
In that particular case, I mixed cases of running `terraform plan|apply` by human operator (User account) and CI pipeline (Service Principal). It's an edge case though.
