### ISSUE TITLE
[DOC] Switch to OpenTofu needs clarification

### ISSUE THREAD

**Issue by mloskot** [claranet/terraform-azurerm-rg#4]
### Description

The Claranet's modules seem to be switching to OpenTofu and deprecating support for Terraform as per https://github.com/claranet/terraform-azurerm-rg/commit/9e9c99236d5cc2be0eccf3399cb1a22a9dd960b0  which added this to the [README.md](https://github.com/claranet/terraform-azurerm-rg/blob/9e9c99236d5cc2be0eccf3399cb1a22a9dd960b0/README.md#usage):

>  ⚠️ Since modules version v8.0.0, we do not maintain/check anymore the compatibility with
  [Hashicorp Terraform](https://github.com/hashicorp/terraform/). Instead, we recommend to use [OpenTofu](https://github.com/opentofu/opentofu/).

As a user of (and occasional contributor to) number of the Claranet modules,  I'd have a couple of questions:
- Does it make sense to drop Hashicorp Terraform support while still relying (heavily) on hashicorp/terraform-provider-azurerm?
- What is the grant plan? Drop Terraform support in v8 line of the Claranet modules?

------

I'm taking the liberty to raise awareness of my questions and mention at least those maintainers of Claranet module who I've had pleasure to interact with: @rossifumax @Shr3ps

**Comment by Shr3ps** [comment]
Hello @mloskot , thanks for this issue ;)

Here are what we plan for v8 (major breaking) of our modules (that we started to upgrade already):
- major module code refactoring: we now implement lots of best bractices taken from both Hashicorp, Google and Microsoft
- using our caf naming provider fork because the original one is no longer maintained: https://github.com/claranet/terraform-provider-azurecaf
- upgrade AzureRM resources with the new major version v4.0
- since some months now, we only use OpenTofu at Claranet (because of the licence). We didn't changed the versions constrains for now, so our modules should be compatible with Terraform 1.3+ (and newer) but because we don't use Hashicorp Terraform anymore, if there is any issue or something that doesn't work anymore with Terraform and our modules, we will not fix it (but open source community is free to open PR is they want). We will only focus on OpenTofu compatibility.

Let me know if it needs more clarifications,

Cheers

**Comment by mloskot** [comment]
Hi @Shr3ps, thank you very much for sharing this.

There is a couple of more issues I'm concerned about:
- What if Hashicorp-developed providers required by Claranet's modules, like https://github.com/hashicorp/terraform-provider-azurerm and https://github.com/hashicorp/terraform-provider-azuread, no longer work with OpenTofu/require Terraform?
- Will Claranet's users require to [move resources](https://developer.hashicorp.com/terraform/tutorials/configuration-language/move-config) when upgrading from v7.x to v8.x or will the v8.x include `move`-s where required?

**Comment by Shr3ps** [comment]
> What if Hashicorp-developed providers required by Claranet's modules, like https://github.com/hashicorp/terraform-provider-azurerm and https://github.com/hashicorp/terraform-provider-azuread, no longer work with OpenTofu/require Terraform?

It's the same for AWS, GCP and many others big providers. If this happens, I'm pretty sure open-source forks will be done by the community. But we're not here today, so let's see how it goes.

> Will Claranet's users require to [move resources](https://developer.hashicorp.com/terraform/tutorials/configuration-language/move-config) when upgrading from v7.x to v8.x or will the v8.x include move-s where required?

Yes, we included moved blocks in the v8 versions. (example: https://github.com/claranet/terraform-azurerm-storage-account/blob/master/r-storage-account.tf)

**Comment by mloskot** [comment]
> (...) we're not here today, so let's see how it goes.

Yup, understood.

> Yes, we included moved blocks in the v8 versions. 

That is awesome!

Thank you.

**Comment by mloskot** [comment]
> We will only focus on OpenTofu compatibility.

Well, my own modules already require Terraform 1.9.x due to use of [input variable validation rules can refer to other objects](https://github.com/hashicorp/terraform/blob/v1.9/CHANGELOG.md#190-june-26-2024) enhancement which is [not yet available in OpenTofu, but planned for 1.9.0](https://github.com/opentofu/opentofu/issues/1336).
Simplifying validation conditions is  not an option, because my modules accept quite complex input objects, often collected from JSON files, for which checking inter-references and data consistency is essential.

Not being able to switch to OpenTofu yet, I will keep using Claranet v7.x modules with Terraform, hopefully not for long.

------

Assuming there is no Claranet document that needs to be updated, I'm happy to close this issue.
Thanks again for your clarifications @Shr3ps

**Comment by mloskot** [comment]
I have just learned that from around the time we had the discussion above, AVM community issued the following [Statement on OpenTofu Support](https://github.com/Azure/Azure-Verified-Modules/discussions/1512)

> As of now, Azure Verified Modules (AVM) fully supports both Bicep and Terraform (...) we are closely monitoring developments, including potential impacts from [IBM's recent acquisition of HashiCorp](https://newsroom.ibm.com/2024-04-24-IBM-to-Acquire-HashiCorp-Inc-Creating-a-Comprehensive-End-to-End-Hybrid-Cloud-Platform).

I hope AzureRM 3.x won't retire too soon, as the current landscape does not make it easy to decide which path to take.

p.s. I'm sharing this not to heat up any discussion, but to gather facts that may be important to other users of Claranet modules in similar suspension as I am.
