### ISSUE TITLE
[BUG] setting "default_tags_enabled" to "true" will convert "environment" tag to "env"

### ISSUE THREAD

**Issue by tomer-1** [claranet/terraform-azurerm-rg#5]
### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### 

### Terraform Version

v1.10.1

### AzureRM Provider Version

v3.117.0

### Affected Resource(s)/Data Source(s)

azurerm_resource_group

### Terraform Configuration Files

```hcl
module "rg" {
  source  = "claranet/rg/azurerm"
  version = "7.1.0"
  environment = "environment"
  client_name = "client"
  stack       = "stack"
  location    = "uksouth"
}
```

### Debug Output/Panic Output

```shell
-/+ resource "azurerm_resource_group" "main_rg" {
      ~ id         = (known after apply)
      ~ name       = "rg-stack-client-environment"
      ~ tags       = {
          ~ "env"                 = "environment"
          ~ "stack"               = "stack"
        }
        # (2 unchanged attributes hidden)
    }
```

### Expected Behaviour

-/+ resource "azurerm_resource_group" "main_rg" {
      ~ id         = (known after apply)
      ~ name       = "rg-stack-client-environment"
      ~ tags       = {
          ~ "environment"    = "environment"
          ~ "stack"               = "stack"
        }
        # (2 unchanged attributes hidden)
    }

### Actual Behaviour

when creating an RG with the default values , the "environment" field gets translated to "env" tag by default.
the only way to fix this is to supply **extra_tags** and set **default_tags_enabled** to **false**

### References

https://registry.terraform.io/modules/claranet/rg/azurerm/7.1.0

**Comment by BzSpi** [comment]
Hello,

Thank you for reporting this issue.

However, this is an expected behavior.  We have chosen to use the `env` tag name since the beginning. If you wish to add an `environment` tag without the env tag, you can call the module this way.

```
module "rg" {
  source  = "claranet/rg/azurerm"
  version = "7.1.0"
  environment = "environment"
  client_name = "client"
  stack       = "stack"
  location    = "uksouth"

  default_tags_enabled = false
  extra_tags = {
    environment = "environment"
  }
}
```
